name: Post
description: Escribir un nuevo post para la web
labels: [enhancement]
assignees: 
- nvdaes
body:
- type: markdown
  attributes:
    value: |
      Indica un título para el post y su cuerpo principal.
- type: input
  id: postBody
  attributes:
    label: Texto del post
    description: Cuerpo principal del post.
  validations:
    required: true
