name: Check for NVDA-2020.4
on:

  push:  
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  update-release-link:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86

    - name: Update release
      run: |
        import re
        import urllib.request
        url = "https://github.com/nvaccess/nvda/releases/latest"
        response = urllib.request.urlopen(url)
        text = str(response.read())
        
        def hasReleaseUpdate():
          if "2020.3" in text:
            return True
          return False
          
        if hasReleaseUpdate():
          with open("main/_layouts/default.html", 'r+', encoding='utf-8') as f:
            text = f.read()
            text = re.sub(".3", ".3", text)
            f.seek(0)
            f.write(text)
            f.truncate()
        else:
          raise Exception("Release not updated yet")
      shell: python 
    

    - name: Checkout NVDA
      uses: actions/checkout@v2
      with:
        repository: nvaccess/nvda
        submodules: true
        ref: release-2020.3
        path: nvda
    - name: Prepare NVDA
      run: scons source user_docs
      shell: cmd

    - name: Move documentation
      run: |
        Move-Item -Path nvda\user_docs\es\G*.html -Destination main\userGuide.html -Force
        Move-Item -Path nvda\user_docs\es\*Referencia*.html -Destination main\commands.html -Force
        Move-Item -Path nvda\user_docs\es\Qu*.html -Destination main\changes.html -Force
    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add main/_layouts/default.html
        git add main/userGuide.html
        git add main/commands.html
        git add main/changes.html
        git commit -m "Update release link and docs"
        git push
        
        