name: Create post

on:
  issues:
    types: 
      - opened
      - reopened
      - edited

jobs:
  add-post:
    name: Add post
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get data
      id: get-data
      uses: actions/github-script@v4
      with:
        script: |
          const number = context.payload.issue.number.toString()
          core.setOutput('number', "#" + number)
          core.setOutput('branch', "issue" + number)
          const title = context.payload.issue.title
          core.setOutput('filename', "_posts/" + title + ".md")
          const author = context.payload.issue.user.login
          const body = context.payload.issue.body   
          const header = `---
          title: 
          permalink: "/x/"
          layout: post
          commentsId: 0
          author: 
          ---
          `
          core.setOutput('body', header + body)
          console.log(author)
    - name: Create PR
      env:
        token: ${{ secrets.GitHub_TOKEN }}
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git checkout -b ${{steps.get-data.outputs.branch}}
        echo "${{steps.get-data.outputs.body}}" > ${{steps.get-data.outputs.filename}}
        git add .
        git commit -m "Add post"
        gh pr create --head --title "Add post" --body "Fixes ${{steps.get-data.number}}" --reviewer nvdaes
        