name: Create post

on:
  issues:
    types: 
      - opened
      - reopened
      - edited

jobs:
  add-post:
    name: Add post
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get data
      id: get-data
      uses: actions/github-script@v4
      with:
        script: |
          const number = context.payload.issue.number
          core.setOutput('number', number)
          const title = context.payload.issue.title
          core.setOutput('title', title)
          const body = context.payload.issue.body
          core.setOutput('body', body)
          const author = context.payload.issue.user.login
          core.setOutput('author', author)
    - name: Create PR
      env:
        BRANCH = format("issue{0}", "${{steps.get-data.outputs.number}}")
        run: echo branch